### ISSUE TITLE
IndexError: pid.append(line[2])

### ISSUE THREAD

**Issue by SimonKitSangChu** [peci1/nvidia-htop#10]
Unexpected IndexError when calling nvidia-htop.py. Error persists regardless the passed arguments/options.

```
nvidia-htop.py --color -l 30
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   45C    P2    27W / 175W |    749MiB /  7981MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 750 Ti  Off  | 00000000:04:00.0  On |                  N/A |
| 33%   33C    P0     2W /  46W |    725MiB /  2002MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/home/tmp/.local/bin/nvidia-htop.py", line 127, in <module>
    pid.append(line[2])
IndexError: list index out of range
```

**Comment by peci1** [comment]
Can you post the output of nvidia-smi?

**Comment by SimonKitSangChu** [comment]
Sure. Here it is.

```
nvidia-smi
Sun Aug  2 13:44:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   50C    P2    27W / 175W |    749MiB /  7981MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 750 Ti  Off  | 00000000:04:00.0  On |                  N/A |
| 33%   30C    P8     1W /  46W |    871MiB /  2002MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2622      C   python                            745MiB |
|    1   N/A  N/A      1356      G   /usr/lib/xorg/Xorg                244MiB |
|    1   N/A  N/A      2262      G   compiz                            139MiB |
|    1   N/A  N/A      2561      G   fcitx-qimpanel                      3MiB |
|    1   N/A  N/A     20219      G   ...ommunity/205/jbr/bin/java        1MiB |
|    1   N/A  N/A     27376      G   ...oken=10729392297284739555      472MiB |
+-----------------------------------------------------------------------------+

```

**Comment by hassaanmahmood** [comment]
I am also getting the same error. After an automatic update on our server machine for nvidia-htop
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:04:00.0 Off |                  N/A |
| 43%   73C    P2   224W / 250W |   7961MiB / 11178MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:06:00.0 Off |                  N/A |
| 23%   26C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
| 23%   22C    P8     7W / 250W |   1535MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
| 23%   20C    P8     7W / 250W |   1707MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:0C:00.0 Off |                  N/A |
| 23%   24C    P8     7W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:0D:00.0 Off |                  N/A |
| 23%   20C    P8     7W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:0E:00.0 Off |                  N/A |
| 23%   22C    P8     8W / 250W |    483MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 00000000:0F:00.0 Off |                  N/A |
| 23%   21C    P8     7W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/usr/local/bin/nvidia-htop", line 120, in <module>
    pid.append(line[2])
IndexError: list index out of range

**Comment by peci1** [comment]
Apparently, the output of `nvidia-smi` changed in driver 450. I attempted a fix in the latest commit. Can you try it out and report if it helped?

**Comment by SimonKitSangChu** [comment]
@peci1 It works perfectly now!

**Comment by veronica320** [comment]
Hi @peci1, thanks for developing this awesome tool! 
I'm still experiencing this error, even though I've installed the latest version from source (1.0.3). I also tried to roll back to [this commit](https://github.com/peci1/nvidia-htop/commit/2aa3388c2dd9e9585cd854d39babb0bed0385dd4) but the error persists.
Could you please take another look? Thanks in advance!

**Comment by peci1** [comment]
Hi @veronica320 , please, post here the complete output of `nvidia-smi` and `ps -o pid,user,%cpu,%mem,etime,command` (you may redact the list of processes as it may contain some sensitive information; it's important to keep the PIDs that correspond to the processes listed in `nvidia-smi`).

**Comment by veronica320** [comment]
@peci1 Thanks for the quick response! Please see below.
Output of `nvidia-smi`:
```
Wed Jul 28 17:50:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 16%   26C    P8    11W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
| 17%   25C    P8     1W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:3D:00.0 Off |                  N/A |
| 16%   24C    P8    20W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:3E:00.0 Off |                  N/A |
| 16%   25C    P8     8W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  On   | 00000000:88:00.0 Off |                  N/A |
| 16%   25C    P8    19W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  On   | 00000000:89:00.0 Off |                  N/A |
| 16%   24C    P8     1W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  On   | 00000000:B1:00.0 Off |                  N/A |
| 16%   24C    P8     1W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  On   | 00000000:B2:00.0 Off |                  N/A |
| 17%   24C    P8    20W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

Output of `ps -o pid,user,%cpu,%mem,etime,command`:
```
  PID USER     %CPU %MEM     ELAPSED COMMAND
48122 xxx   0.0  0.0       02:10 -bash
48227 xxx   0.0  0.0       00:00 ps -o pid,user,%cpu,%mem,etime,command
```

Though there're no gpu processes, there's still the IndexError when running `nvidia-htop.py -c`:
```
Wed Jul 28 17:54:24 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 16%   25C    P8     9W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
| 16%   25C    P8     1W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:3D:00.0 Off |                  N/A |
| 16%   24C    P8    19W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:3E:00.0 Off |                  N/A |
| 16%   25C    P8     8W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  On   | 00000000:88:00.0 Off |                  N/A |
| 16%   24C    P8    18W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  On   | 00000000:89:00.0 Off |                  N/A |
| 16%   24C    P8     1W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  On   | 00000000:B1:00.0 Off |                  N/A |
| 16%   24C    P8     2W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  On   | 00000000:B2:00.0 Off |                  N/A |
| 16%   24C    P8    20W / 250W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "path/to/nvidia-htop.py", line 127, in <module>
    pid.append(line[2])
IndexError: list index out of range
```

**Comment by peci1** [comment]
@veronica320 Is this still a problem for you? Did you try with the latest version of nvidia-htop?
