### ISSUE TITLE
issue install on proxmox 6.4

### ISSUE THREAD

**Issue by killmasta93** [peci1/nvidia-htop#23]
Hi 
Currently tried installing but when i run im getting this issue

```
nvidia-htop.py
Traceback (most recent call last):
  File "/usr/local/bin/nvidia-htop.py", line 57, in <module>
    ps_call = subprocess.run('nvidia-smi', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi': 'nvidia-smi'

```

```
 sudo lshw -C display
  *-display
       description: VGA compatible controller
       product: G98 [GeForce 9300 GS]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:40 memory:f6000000-f6ffffff memory:e0000000-efffffff memory:f4000000-f5ffffff ioport:bc80(size=128) memory:c0000-dffff

```

**Comment by peci1** [comment]
You need to install the standard Nvidia drivers that provide the nvidia-smi command (I think particularly nvidia-tools or nvidia-utils or how is it called).

It is a "hidden" dependency of this package - it can't be automatically installed by pip because the driver can't be installed by pip.
